apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-image
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: image-name
          - name: image-tag
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=/workspace"  # Use the Dockerfile and application code in /workspace
          - "--dockerfile=/workspace/Dockerfile"
          - "--destination={{inputs.parameters.image-name}}:{{inputs.parameters.image-tag}}" # Build and tag the image properly
          - "--tar-path=/workspace/built-image.tar"  # Save the image as a tarball for further steps
        volumeMounts:
          - name: workspace-volume
            mountPath: /workspace
