apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: clone-repo
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: repo-url
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            set -e; \
            if [ -z "$SSH_PRIVATE_KEY" ]; then echo "SSH key not set"; exit 1; fi; \
            mkdir -p ~/.ssh && \
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && \
            chmod 600 ~/.ssh/id_rsa && \
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && \
            echo "Cloning repository to temporary directory..."; \
            TEMP_DIR=$(mktemp -d) && \
            git clone {{inputs.parameters.repo-url}} $TEMP_DIR && \
            echo "Moving repository content to /workspace..."; \
            mv $TEMP_DIR/* /workspace/ && \
            mv $TEMP_DIR/.[!.]* /workspace/ 2>/dev/null || true && \
            echo "Contents of /workspace:" && \
            ls -l /workspace && \
            echo "Cleaning up temporary directory..."; \
            rm -rf $TEMP_DIR
        volumeMounts:
          - name: workspace-volume
            mountPath: /workspace
        env:
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: argo-workflow-ssh-key
                key: ssh-privatekey
