apiVersion: v1
kind: Secret
metadata:
  namespace: argo
  name: dockerhub-credentials
type: Opaque
data:
  username: {{ env "DOCKERHUB_USERNAME" | b64encode }}
  password: {{ env "DOCKERHUB_TOKEN" | b64encode }}
